### ISSUE TITLE
Breadcrumbs Overflow

### ISSUE THREAD

**Issue by ChetCorey** [ChetCorey/duke-data-service-portal#5]
In Dashboard view, the Breadcrumbs overflow their container.

![responsivelistitemsbug itemactionbuttionsbug breadcrumbwrappingbug](https://user-images.githubusercontent.com/7772027/38633905-03869ffc-3d8f-11e8-8c60-ec3f203247af.gif)

**Comment by caseychoiniere** [comment]
Give your <Paper/> `styles.breadcrumb` height: 36px to minHeight: 36px and this will wrap.

**Comment by ChetCorey** [comment]
Thanks, @caseychoiniere

Branch: Dashboard
commit a284d92394e2118b3a44f6b6e99fedc399d53abd

<img width="975" alt="breadcrumbwrap" src="https://user-images.githubusercontent.com/7772027/38697848-22894e2c-3e61-11e8-8468-cc1f60eedae2.png">
