### ISSUE TITLE
ListItems Not Updating After Home Link Click

### ISSUE THREAD

**Issue by ChetCorey** [ChetCorey/duke-data-service-portal#7]
ListItems is not being updated with Projects after HomeLink in Dashboard

![listitemsnotupdatingafterhomelink](https://user-images.githubusercontent.com/7772027/38634658-30ce6948-3d91-11e8-9ab3-11d08dc73a1d.gif)

**Comment by caseychoiniere** [comment]
Is this a bug? I always actually wondered about the UX of having projects listed in both the tree view and the list view simultaneously . It's a tad confusing. I guess it's necessary for being able to take action through the drop down menu on projects though.

**Comment by ChetCorey** [comment]
I see where you're coming from.
I was also thinking it would also be a better UI for mobile view. This way you can hide the TreeList and you can still do everything you want the ListItems and Breadcrumbs

**Comment by caseychoiniere** [comment]
Yep, this is a tricky one. I'm not sure what the proper UX is here. It's worth thinking about though.

**Comment by ChetCorey** [comment]
I belive this is the desired behavior, also all of the other breadcrumb links are working

![breadcrumbhomebuttonworking](https://user-images.githubusercontent.com/7772027/38884434-97393b30-423d-11e8-8a83-e30a480056fe.gif)

**Comment by ChetCorey** [comment]
I belive this is the desired behavior, also all of the other breadcrumb links are working

![breadcrumbhomebuttonworking](https://user-images.githubusercontent.com/7772027/38884496-d13ffa08-423d-11e8-84d7-619ae3bfce70.gif)
